### PR TITLE
First draft of scope checking

### PR DESCRIPTION
**Pull request by LightAndLight**
A Python program can be badly-scoped in five ways:

1. It contains `global` statements
2. It contains `nonlocal` statements
3. It contains `del` statements (this will need to be refined)
4. Variables declared inside control statements are referenced from the outside
5. The variable is not in scope

If anything from 1-4 are present in a module then you can't generally decide if any particular variable is in scope, because the scoping is determined by the execution of the program. If 1-4 are false, then static scope checking is sound.

### CODE REVIEW

**Comment by tonymorris** [comment]
Is this a tool that depends on the core job of hpython, or a part of hpython?

**Comment by LightAndLight** [comment]
I don't know how to determine which one it is. `hpython` currently contains an edsl for writing python, and this will help validate code the user writes with the edsl, so I lean to the latter. If you think it's the former then we should get more granular with the project as a whole.

**Comment by tonymorris** [comment]
I suspect it is a bit independent of hpython, in which case, I think it could be its own project. Even if just a small tool to start off with.

**Comment by LightAndLight** [comment]
In that case, I think that the edsl, indentation validation, and syntax validation should also be factored out too. Maybe their relevant optics too (e.g. `indents :: Traversal stuff Indentation` -> hpython-indentation package)

That leaves `hpython` as just the parser, printer and AST.

**Comment by LightAndLight** [comment]
Or maybe leave the syntax validation in `hpython`, because it can be argued to "determine whether or not the AST is python", and then factor out indentation and scoping because they're auxiliary.

**Comment by tonymorris** [comment]
We could potentially leave it all part of hpython, with a module separation, with a view to split them out when it comes time to know how we are going to deploy our "tools on top of hpython."

**Comment by LightAndLight** [comment]
They're already separate modules, and I've engineered this stuff so that splitting it off in the future won't require any code changes.

**Comment by tonymorris** [comment]
:+1:

**Pull request merged**
