### PR TITLE
Commasep monoid

### PR DESCRIPTION
**Pull request by gwils**

### CODE REVIEW

**Comment by LightAndLight** [comment]
Ergh yeah I forgot about this function. I think maybe the append function should add in a `[Space]` instead of a `[]`, then `listToCommaSep` would be a semigroup/monoid homomorphism. What do you think?

**Comment by gwils** [comment]
I think if we're going to make a choice, I like `[Space]` more than `[]`, but only because that's how I like to lay out code.

It might be better to not have semigroup/monoid and instead make the append function take a `[Whitespace]`.

A third option is to have the function that takes `[Whitespace]` and then just make a choice in the semigroup/monoid (which I think would be the most convenient)
`(<>) = appendCommaSep [Space]`

My favourite is the third option.

**Comment by LightAndLight** [comment]
Yeah I think the third option is the best, especially if you plan to make commasep non-internal

**Comment by gwils** [comment]
I'll write the code and push another commit.
I do intend to make CommaSep non-internal. To me a necessary condition (but not sufficient) for hpython to be "ready" is for none of the examples to use `Internal` code.

**Comment by gwils** [comment]
More commits have been pushed.

Should `listToCommaSep` and `listToCommaSep1` also take a whitespace argument? Should there be `listToCommaSep'` and `listToCommaSep1'` that default them to `[Space]`?

I'm not sure I can be bothered since you can just `foldMap CommaSepOne`, so I'm in favour of leaving them as they are.

**Comment by LightAndLight** [comment]
Should be fine for now

**Pull request merged**
